### ISSUE TITLE
Need to disable ALL MOBS in protected area

### ISSUE THREAD

**Issue by Neerdex** [RevivalPMMP/PEXProtection#14]
Hello! I need to protect area from all mobs, not only from monsters like spiders, zombies etc, but from cows, pig and others too. How can i do this?

**Comment by 95CivicSi** [comment]
Are you still having problems with this?

**Comment by Neerdex** [comment]
Yes. Its a big problem for me :(
I need help with this.

**Comment by 95CivicSi** [comment]
Ok.  I'll look into it today.

**Comment by Neerdex** [comment]
Thank you! I will wait any news from you!

**Comment by 95CivicSi** [comment]
A Pull Request was created to fix this issue.  You can find it here:  

https://github.com/RevivalPMMP/PEXProtection/pull/15

If you are able to test by using the source, that would be helpful.

**Comment by Neerdex** [comment]
Some errors in console:
Warning: in_array() expects parameter 2 to be array, boolean given in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 89

Notice: Undefined index: xPos in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 94

Notice: Undefined index: yPos in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 95

Notice: Undefined index: zPos in D:\MCPE\GenisysPRO-TESTING\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 96

Notice: Undefined index: level in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 97

Notice: Undefined index: radius in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 100

Warning: in_array() expects parameter 2 to be array, boolean given in D:\MCPE\plugins\PEXProtection_v0.1.1\src\RevivalPMMP\PEXProtection\Main.php on line 100

**Comment by 95CivicSi** [comment]
Did you update or remove your previous centers.yml file?

**Comment by Neerdex** [comment]
Remove

**Comment by Neerdex** [comment]
Same shit with update

**Comment by 95CivicSi** [comment]
Is this happening when you try to add a new area?

**Comment by Neerdex** [comment]
No, area adds correctly, but mobs dont spawn in all world if i add it. This error happens before and after adding area.

**Comment by 95CivicSi** [comment]
I need some info to recreate this issue so I can fix it.

Server Software Version:
PureEntitiesX Version:
PHP Version:
Copy of centers.yml and config.yml

**Comment by Neerdex** [comment]
Hm, i think errors can happens because i change server core to GenisysPRO... :-/
Mb i need to rewrite it first for GenisysPRO.

**Comment by 95CivicSi** [comment]
For the record, I have tested this on PocketMine-MP version 1.7dev-345 with API 3.0.0-ALPHA9 with no errors.

I can't speak directly for PEXProtection but I imagine that it somewhat follows other ideals from RevivalPMMP in that there is no support for forks/spoons of PocketMine.  I know for sure that PureEntitiesX does not support anything other than PocketMine-MP.

**Comment by 95CivicSi** [comment]
Solved in PR #15
