### ISSUE TITLE
Request - disable spawning per-world

### ISSUE THREAD

**Issue by joshnorth** [RevivalPMMP/PEXProtection#3]
Any way to add ability to disable spawning on certain worlds?  Or even better, limit spawning per-world to certain types? 
Example - I have a "water world" for building - I'm fine if sea creatures spawn but when cows and pigs and spiders are raining down from the sky on users ships it's a little weird :)

**Comment by hiilikewiki** [comment]
Please use our forums for this (Link in README)

**Comment by jasonw4331** [comment]
it's still a good idea

**Comment by Sandertv** [comment]
Implemented in latest commit.

**Comment by Sandertv** [comment]
I'll add per-entity spawn disabling later.
