### ISSUE TITLE
Plugin not work using Tesseract

### ISSUE THREAD

**Issue by ghost** [RevivalPMMP/PEXProtection#4]
Plugin not work using Tesseract

**Comment by Sandertv** [comment]
'Plugin not work using Tesseract' is not a proper description. PureEntitiesX and with that PEXProtection is designed for PocketMine, and might not work with spoons. IF you decide to post an issue from Tesseract, please at least tell us why it doesn't work.

**Comment by ghost** [comment]
Animals can spawn in area.

I'm used /pexprotection add spawn 200

And animals spawn on this radius

**Comment by Sandertv** [comment]
Is there any error given when they spawn?

**Comment by ghost** [comment]
No.

**Comment by JIaBpyxa** [comment]
Same trouble. There is no error given, but mobs still spawning.
Is this right that X and Z without quotes, except Y.
![image](https://cloud.githubusercontent.com/assets/9865123/23981612/a1b592ae-0a29-11e7-8c46-f328d7120ac0.png)

**Comment by ghost** [comment]
same.

**Comment by Sandertv** [comment]
If it does work with PocketMine, there's nothing I can do about it; It has to be a Tesseract issue.
