### ISSUE TITLE
Plugin is glitchy on Tesseract

### ISSUE THREAD

**Issue by AnUnknownPerson** [RevivalPMMP/PEXProtection#7]
While using PureEntitiesX Sheep for some reason climb walls and horses can't be hurt spiders glitch and fly and if you punch a chicken you lagg! PLEASE FIX THIS
And I used  the PEXProction plugin to block from spawning and it still spawns!

**Comment by Sandertv** [comment]
We develop these plugins in our own time, so please have a little patience. First of all, this is not the PureEntitiesX repository, and these issues have already been reported. Tesseract does not seem to work for some reason. I don't know why, but it's already been reported. Don't make duplicated issues please.
